name: Lint and Test

on:
    pull_request:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: oven-sh/setup-bun@v2
                with:
                    bun-version: 1.1.29
            -   run: bun install
            -   run: bun lint
            -   run: bun test
